services:
  amniotic:
    container_name: amniotic
    hostname: amniotic
    image: fmtr/amniotic:latest
    restart: unless-stopped

    # Expose container port to host
    ports:
      - "8007:8080"  # Amniotic audio stream over HTTP port.

    # Mount local audio and config directories to container
    volumes:
      - ./audio:/amniotic/audio
      - ./config:/amniotic/config

    environment:
      # Home Assistant URL and token
      AMNIOTIC__HA_CORE_API: "http://homeassistant.local:8123/api"  # API URL for your HA instance
      SUPERVISOR_TOKEN: "your_long_lived_access_token"              # HA access token, to let Amniotic interact with media players. Generate here. https://my.home-assistant.io/redirect/profile_security/

      # MQTT settings
      AMNIOTIC__MQTT__HOSTNAME: "mqtt.local"   # MQTT broker hostname or IP
      #AMNIOTIC__MQTT__PORT: "1883"             # Optional MQTT port (defaults to 1883 for TCP)
      #AMNIOTIC__MQTT__USERNAME: "mqtt_user"    # Optional MQTT username
      #AMNIOTIC__MQTT__PASSWORD: "mqtt_pass"    # Optional MQTT password

      # Application-specific settings
      AMNIOTIC__STREAM_URL: "http://<ip_or_hostname>:8007"  # URL where media players can access Amniotic on your network.
      AMNIOTIC__PATH_AUDIO: "/amniotic/audio"               # Path inside container for audio files (mapped above)
      AMNIOTIC__PATH_CONFIG: "/amniotic/config"              # Path inside container for config files (mapped above)

    # No need for root
    user: "1000:1000"
