[build-system]
requires = ["setuptools>=82", "wheel"]
build-backend = "setuptools.build_meta"

[tool.corio.metadata]
version = "1.9.19-alpha000"
port = 7
base = "python"
description = "A multi-output ambient sound mixer for Home Assistant"
org_github = "fmtr"
org_friendly = "Frontmatter AI"
is_client = false
scripts = []
services = []
keywords = ["ambient sound", "audio", "white noise", "masking", "sleep"]
is_pypi = true
is_dockerhub = true

[tool.corio.metadata.setup]

[tool.setuptools]
script-files = ["scripts/vlc-tn.service"]

[tool.setuptools.packages.find]
where = ["."]
include = ["amniotic*"]
namespaces = false

[tool.setuptools.package-data]
amniotic = ["pyproject.package.toml"]

[tool.uv.sources.corio]
path = "../corio"
editable = true

[tool.uv.sources.haco]
path = "../haco"
editable = true

[tool.tox]
requires = ["tox>=4.22", "tox-uv>=1"]
env_list = ["amniotic"]

[tool.tox.env.amniotic]
description = "Run amniotic tests."
deps = ["corio[test]~=2.3.6"]
commands = [["python", "-m", "pytest", "-q", "amniotic/tests"]]

[project]
name = "amniotic"
version = "1.9.19-alpha000"
description = "A multi-output ambient sound mixer for Home Assistant"
readme = "README.md"
license = "Apache-2.0"
keywords = ["ambient sound", "audio", "white noise", "masking", "sleep"]
requires-python = ">=3.13"
dependencies = ["corio[api,av,caching,debug,ha.api,http,logging,mqtt,path.app,sets,tabular,version.dev,yaml,youtube]~=2.3.6", "haco~=0.3.9", "psutil"]

[[project.authors]]
name = "Frontmatter AI"
email = "innovative.fowler@mask.pro.fmtr.dev"

[project.optional-dependencies]
test = ["corio[test]~=2.3.6"]

[project.scripts]
amniotic = "amniotic.entrypoint:main"

[project.urls]
Homepage = "https://github.com/fmtr/amniotic"
