FROM fmtr/python

RUN apt update -y
RUN apt install -y --no-install-recommends ffmpeg pulseaudio vlc alsa-utils

WORKDIR /fmtr/fmtr/tools
COPY --from=tools ../requirements.py .
RUN python requirements.py logging,yaml,version > requirements.txt
RUN pip install -r requirements.txt --no-cache-dir

WORKDIR /fmtr/amniotic
COPY --from=amniotic ../requirements.py .
RUN python requirements.py > requirements.txt
RUN pip install -r requirements.txt --no-cache-dir



